[package]
name = "wakfudecrypt"
version = "0.1.0"
authors = ["jac3km4 <gh@jekky.dev>"]
edition = "2024"

[dependencies]
byteorder = "1"
zip = { version = "4", default-features = false, features = [ "deflate" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
